# Site settings
title: Jon Todd
email: jonrtodd@gmail.com
description: "This is my tech blog containing random thoughts and code snippets" 
baseurl: ""
url: "http://jontodd.github.io"

# Build settings
markdown: kramdown
permalink: pretty
