# Site settings
title: Jon Todd
email: jonrtodd@gmail.com
description: "This is my tech blog containing random thoughts and code snippets" 
baseurl: ""
url: "http://dev.jontodd.com"

# Build settings
markdown: kramdown
permalink: pretty

analytics:
  provider: google
  google:
    tracking_id: UA-51485030-1

